import { Inter } from 'next/font/google'
import './globals.css'
import Header from './Components/Layout/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <main className="max-w-6xl p-4 mx-auto">
          <Header />
          {children}
        </main>
      </body>
    </html>
  )
}
